import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import AppProviders from "@/components/AppProviders";
import Appbar from "@/components/Appbar";

const quickSand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "child registration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quickSand.className}>
        <AppProviders>
          <Appbar />
          <div className="h-[0px] lg:h-[60px] inline-block" />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
